### ISSUE TITLE
Collider Creator not responding

### ISSUE THREAD

**Issue by Lewox** [CleanCut/ultimate_rust2#10]
Hi Nathan!

I'm following your course and tried to create the collider myself and the program gets stuck after the first click and won't recover.

I'm running it from CLion's console on Windows 10, everything is updated.

**Comment by CleanCut** [comment]
Can you try running it from outside of CLion's console to see if that's the problem?

**Comment by Lewox** [comment]
Hi Nathan, I just tried from CMD and got the same result, this is the log:

![image](https://github.com/CleanCut/ultimate_rust2/assets/9854935/533ebf24-eb65-4888-a216-4e8804f380d5)

Music is in the background, and the initial sprites can be seen, but the window is frozen a couple of seconds later.

**Comment by CleanCut** [comment]
🤔 Hmm. Here's a few things to try:

- Make sure you are using the most up-to-date version of `rusty_engine` (version `6.0.0` at the moment)
- Make sure you are using the latest stable version of Rust (`rustup update`)
- Make sure your Vulkan graphics drivers are up-to-date (and your Windows is up-ta-date)
- Put your code on GitHub and let me look at it. 😄

**Comment by Lewox** [comment]
Hi Nathan!

I tried updating Windows, but there is not much to update, only the Antivirus database.

I tried `rustup update`, it did update Rust but that didn't change anything.

I updated the driver, and although I think it was the latest version, it didn't change anything.

What worked for me was updating to 6.0.0 from 5.2.0, 5.2.1 had the same issue.
