### ISSUE TITLE
Truncated code listing in class::resource::slides

### ISSUE THREAD

**Issue by BonjourGit** [CleanCut/ultimate_rust2#5]
Hi,

There is formatting issue with code listing in the class handout slides (pdf).
The line spacing between code lines seems to be too large.
A long code listing can thus be truncated and becomes incomplete.
Please see the following example excerpt:

![image](https://user-images.githubusercontent.com/34569855/144586573-dd4540fc-c87f-45ea-ac91-e18b7ea42d12.png)

It will be very much appreciated if the formatting issue can be fixed.

Many thanks!

**Comment by CleanCut** [comment]
That looks...terrible! I'm afraid I have no control over how O'Reilly mangles my slides, but here is a screenshot of what it _should_ look like!

![slide497](https://user-images.githubusercontent.com/5838512/144677908-46dfebdf-dea1-4198-b242-0a3034a6c3c6.png)
